version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysqltest
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
