version: '3'
services:
  test_es:
    #curl
    image: appropriate/curl
    container_name: test_es
    # command: ["curl", "http://es:9200"]
    # multiple commands
    volumes:
      - ./curl.sh:/curl.sh
    command: sh /curl.sh
    depends_on:
      - es
    networks:
      - my_network
    

  allinone:
    image: xzchaoo/lookout-allinone:1.6.0-SNAPSHOT
    container_name: allinone
    ports:
      - "7200:7200"
      - "9090:9090"
    volumes:
      - ./foo.properties:/home/admin/deploy/foo.properties
    environment:
      - JAVA_OPTS=-Dlookoutall.config-file=/home/admin/deploy/foo.properties
      # 如果您需要添加其他 JVM 系统属性，您可以通过在此处指定多个 JAVA_OPTS 环境变量来实现
    depends_on:
      - es
    networks:
      - my_network
  es:
    image: elasticsearch:5.6
    container_name: es
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
